import type { Metadata } from "next";
import "./globals.css";

import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen bg-[#FEFAE0] text-[#4A3728] font-sans selection:bg-[#D4A373] selection:text-white overflow-x-hidden flex flex-col">
          <Navbar />

          <main>
            {children}
          </main>

          <Footer />
        </div>
      </body>
    </html>
  );
}
